### ISSUE TITLE
unused const errstream_t& error ...?

### ISSUE THREAD

**Issue by laeos** [kg7oem/oemros#5]
https://github.com/kg7oem/oemros/blob/f3054f82319a59fb43a35c5280587a02d524dd8c/src/system.cpp#L72

I guess you're just using errstream_t to force it to emit current errno (like printf %m?) 

then errstream_t errstream should probably also be const anyway.

**Comment by kg7oem** [comment]
Yes that is correct - I was just using it to get something like printf %m but I think that wasn't a very good way to do it. [I removed errstream and switched to using errnostr()](https://github.com/kg7oem/oemros/commit/8320df52a67404a5ccf4bd0e8a8f8ea2811bb2ac) in the logging functions when reporting errors.

I think removing that thing is the best way to solve this.
